#!/usr/bin/env bash
# This script installs nginx web server
# And also starts the service

apt-get update
apt-get -y install nginx

# making directory a directory /html
mkdir /new/nginx/html
# making a new file index.html
touch /new/nginx/html/index.html
# Redirecting the string to be dislayed to the default location
echo 'Hello World!' > /new/nginx/html/index.html
# Restarting nginx
service nginx restart
