#!/usr/bin/env bash
# This script Configurs Nginx server
# To have a custom 404 page that contains
# The string Ceci n'est pas une page


stored=/etc/nginx/sites-available/default

apt-get -y update
apt-get install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

touch /etc/nginx/html/404.html

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > $stored

service nginx restart
