#!/usr/bin/env bash
# This script Configure Nginx so that its HTTP
# Response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname
# Of the server Nginx is running on

stored=/etc/nginx/sites-available/default

apt-get -y update
apt-get install -y nginx

mkdir -p /etc/www/html
touch /etc/www/html/index.html
echo "Hello World!" > /etc/www/html/index.html
touch /etc/www/html/404.html
echo "Ceci n'est pas une page" > /etc/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://youtube.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/www/html;
      internal;
    }
}" > $stored
# Restart nginx after installation
service nginx restart
