#!/usr/bin/env bash
# This script generates a MySQL dump
# And creates a compressed archive out of it
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
