#!/usr/bin/env bash
# This script configures nginx to listen on port 80 and also stops nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
