#!/usr/bin/env bash
# This script manages the manage_my_process file
# And displays different srings depending on the process
# Defining the case function
case $1 in
	"start")
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo 'manage_my_process started'
		;;
	"restart")
		process_id=$(cat /var/run/my_process.pid)
		kill -s SIGSTOP $process_id
		rm /var/run/my_process.pid
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo 'manage_my_process restarted'
		;;
	"stop")
		process_id=$(cat /var/run/my_process.pid)
		kill -s SIGSTOP $process_id
		rm /var/run/my_process.pid
		echo 'manage_my_process stopped'
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		;;
esac
