#!/usr/bin/env bash
# This script manages the manage_my_process file
# And displays different srings depending on the process
# Defining the case function
if [ "$1" == "start" ]
then
	sudo ./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
	sudo kill "$(pgrep -f manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	sudo kill "$(pgrep -f manage_my_process)"
	rm /var/run/my_process.pid
	sudo ./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"

else 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
