#!/usr/bin/env bash
# This script displays numbers 1-100 and FIZZBUZZ in a list format
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# Define for loop
for n in {1..100}
do
	if [ $((n % 3)) -eq 0 ]  &&  [ $((n % 5)) -eq 0 ]
	then
		echo "FIZZBUZZ"
	elif [ $((n % 3)) -eq 0 ]
	then
		echo "FIZZ"
	elif [ $((n % 5)) -eq 0 ]
	then
		echo "BUZZ"
	else
		echo "$n"
	fi
done
