#!/usr/bin/env bash
# This script displays numbers 1-100 and FIZZBUZZ in a list format
# Define for loop
for n in {1..100}
do
	if [ $((n % 3)) -eq 0 ]  &&  [ $((n % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((n % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((n % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$n"
	fi
done
