#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# Define while loop
while read line;
do
	if [ -n "$line" ] && [ -n "$uid"] && [ -n "$uid" -eq "$uid" ] 2>"/dev/null"
	then
		echo "Username: $username"
		echo "User_ID: $uid"
		echo "Home_Directory: $home"
		echo ""
	fi
done < "/etc/passwd"
