#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code
# And displays data ordered from greatest to the lowest
# Number of occurences
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
