#!/usr/bin/env bash
# This script displays Best School 10 times but 9th loop display hi
# Initialize the loop
n=1
# Iterate the loop 10 times
while [ $n -le 10 ]
do
	# Check the value of n
	if [ $n -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
	# Display Best School
	echo "Best School"
	fi
	n=$((n+1))
done
