#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# Initializing hours and minutes
hour=0
minute=1

# Define while loop for hours
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	# Define while loop for minutes
	while [ $minute -le 59 ]
	do
		echo "$minute"
		# Increment minutes
		minute=$((minute+1))
	done
	# Increment hours
	hour=$((hour+1))
done
