#!/usr/bin/env bash
# This script checks if a file exists, or exists and empty
# Assigning a file name to filename
filename="school"

if [ -e "$filename" ]
then
	echo "school file exists"
	if [ -s "$filename" ]
	then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi

	if [ -f "$filename" ]
	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
