#!/usr/bin/env bash
# This script configures the container
# To allow nginx to listen at port 8080.

# Stop Apache if running
service apache2 stop
pkill apache2

# Update Nginx server block configuration
NGINX_CONFIG='/etc/nginx/sites-available/default'
SERVER_CONFIG="
server {
    listen *:8080 default_server;
    listen [::]:8080 default_server ipv6only=on;
    root /usr/share/nginx/html;
    index index.html index.htm;
    server_name localhost;
    location / {
        try_files \$uri \$uri/ =404;
    }
}"
printf "%s" "$SERVER_CONFIG" > "$NGINX_CONFIG"

# Set ownership and permissions
chown nginx /etc/nginx/nginx.conf
sudo -u nginx chmod u+r /etc/nginx/nginx.conf
# Restart Nginx
sudo -u nginx service nginx restart
