#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080

# kill apache2 instances (running on 8080 on this server)
service apache2 stop
pkill apache2

# Configure nginx to run on port 8080
NGINX_CONFIG='/etc/nginx/sites-available/default'
CONFIG_SERVER="
server {
	listen 8080 default_server;
	listen [::]:8080 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		try_files $uri $uri/ =404;
	}
}"
printf "%s" "$CONFIG_SERVER" > "$NGINX_CONFIG"

chown nginx /etc/nginx/nginx.conf
sudo -u nginx chmod u+r /etc/nginx/nginx.conf

# Restart nginx
sudo -u nginx service nginx restart
