#!/usr/bin/env bash
# This script Configures nginx to be be running as nginx user
service apache2 stop
chown nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx chmod u+r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
