#!/usr/bin/env bash
# This script configures ssh client
# to refuse to authenticate using a password

    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthenticate yes
    GSSAPIDelegateCredentials no

# Adding the IP address for testing purposes
Host 54.158.211.3
    IdentityFile ~/.ssh/school
    protocol 2
