#!/usr/bin/env bash
# This script configures ssh client
# Adding the IP address for testing purposes
Host 67.202.31.142
    IdentityFile ~/.ssh/school
    preferredAuthentication publickey
    passwordAuthentication no
